<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
?>
<header class="page-header alothemes">
    <div class="header">
		<div class="header-top">
			<div class="container">
				<div class="row">
					<div class="top-left col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->getChildHtml('welcometop'); ?>
						<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('call-us')->toHtml();?>
					</div>
					<div class="top-right col-md-6 col-sm-6 col-xs-12">
						<div class="header-setting">
							<?php echo $this->getChildHtml('currency') ?>
							<?php echo $this->getChildHtml('store_language'); ?>
							<div class="settting-switcher">
								<div class="dropdown-toggle toggle-tab">
									<div class="text-setting"><?php echo __('My Account'); ?></div>
								</div>
								<div class="dropdown-switcher toggle-content">
									<div class="top-links-alo">
										<div class="header-top-link">
											<?php /*echo $this->getChildHtml('header.links');*/ ?>
											<?php
												$objectManagerlogin = \Magento\Framework\App\ObjectManager::getInstance();
												$customerSession = $objectManagerlogin->get('Magento\Customer\Model\Session');
											?>
												<?php if($customerSession->isLoggedIn()) { ?>
													<ul class="my-account-links">
														<li class="order"><a href="<?php echo $block->getUrl('sales/order/history'); ?>"><?php echo __('Orders') ?></a></li>
														<li class="order"><a href="<?php echo $block->getUrl('customer/address'); ?>"><?php echo __('Addresses') ?></a></li>
														<li class="order"><a href="<?php echo $block->getUrl('vault/cards/listaction'); ?>"><?php echo __('Payment') ?></a></li>
														<li class="order"><a href="#"><?php echo __('Dream Credits') ?></a></li>
														<li class="order"><a href="<?php echo $block->getUrl('csmessaging/customer/ainbox'); ?>"><?php echo __('Inbox') ?></a></li>
														<li class="order"><a href="<?php echo $block->getUrl('customer/account'); ?>"><?php echo __('Profile') ?></a></li>
													</ul>
													<a href="<?php echo $block->getUrl('customer/account/logout'); ?>"><?php echo __('LOGOUT') ?></a>
												<?php }else { ?>
													<p class="returning"><?php echo __('Returning Customer') ?></p>
													<h3 class="sign-in"><a href="<?php echo $block->getUrl('customer/account/login'); ?>"><?php echo __('Sign In') ?></a></h3>       
													<p class="dont-have-account"><?php echo __('Don\'t have an account') ?></p>
													<h3 class="sign-up"><a href="<?php echo $block->getUrl('customer/account/create'); ?>"><?php echo __('Sign Up') ?></a></h3>
													<?php
												}
												?>
										</div>
									</div>
								</div>
							</div>
							<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('support')->toHtml();?>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="header-content header-sticker">
			<div class="container">
				<div class="row">
				    <div class="content-logo col-md-3 col-xs-12">
						<div class="header-logo">
							<?php echo $this->getChildHtml('logo'); ?>
						</div>
					</div>
					
					
					<div class="content-seach col-md-6 col-sm-6 col-xs-12">
						<div class="search-area header-search">
							<?php echo $this->getChildHtml('top.search'); ?>
						</div>
					</div>
					
					<div class="content-other col-md-3 col-xs-12">
						<div class="wishlist">
							<a href="<?php echo $this->getUrl('wishlist') ?>"><?php echo __('My Wishlist') ?></a>
						</div>
						<div class="compare">
							<a href="<?php echo $block->getUrl('customer/account'); ?>"><?php echo __('My Account') ?></a>
						</div>
						<div class="content-cart menu-mobile">
							<div class="tool-header">
								<?php echo $this->getChildHtml('minicart'); ?>
								
							</div>
						</div>
					</div>
					<div class="mobile-nav">
					<span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
					<div class="logo"><a href="<?php echo $block->getUrl(''); ?>"><img src="<?php echo $block->getLayout()->getBlock('logo')->getLogoSrc() ?>"/></a></div>
						<ul>
							<li class="search">
								<span class="search-box"><?php echo __('Search') ?></span>
							</li>
							<li class="cart"><a href="<?php echo $block->getUrl('checkout/cart'); ?>"><?php echo __('Cart'); ?></a></li>
						</ul>							
					</div>
					<div class="search-mobile header-search">
						<?php echo $this->getChildHtml('top.search'); ?>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12">
						<?php echo $this->getChildHtml('navigation.sections'); ?>
					</div>
				</div>
			</div>
		</div>
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('service-header')->toHtml();?>
		<div class="header-bottom">
			<div class="container">
				<div class="row">
				   <div class="col-sm-3 vertical-menu menu-mobile-none hidden-xs hidden-sm menu-mobile-none">
						<?php echo $this->getChildHtml('vmenu'); ?>
					</div>
					
					<div class="col-sm-3 col-md-2 group-link-main-menu">
						
					</div>
				</div>
			</div>
		</div>
	</div>
</header>
<script>
	require(["jquery"], function($){
		$(document).ready(function() {
			$(".mobile-nav .search-box").click(function(){
				$(".search-mobile").toggleClass("active");
				$(".mobile-nav .search-box").toggleClass("active");
			});

			$(".mobile-nav .account").click(function(){
				$(".my-account-links-mobile").show("active");
			})
		});
	});

</script>