<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php

/**
*  General template for displaying group of blocks devided into sections
*/

$group = $block->getGroupName();
$groupCss = $block->getGroupCss();
$groupBehavior = $block->getGroupBehaviour() ? $block->getGroupBehaviour() : '{"tabs":{"openedState":"active"}}';
?>

<?php if ($detailedInfoGroup = $block->getGroupChildNames($group, 'getChildHtml')):?>

<div class="sections <?= /* @escapeNotVerified */ $groupCss ?>">
    <div class="close_mobile"><span><?php echo __('close'); ?></span></div>
    <div class="hi">
        <div class="logo">
            <a href="<?php echo $block->getUrl(''); ?>">
                <img src="<?php echo $block->getLayout()->getBlock('logo')->getLogoSrc() ?>" />
            </a>
        </div>
        
        <?php
                $objectManagerlogin = \Magento\Framework\App\ObjectManager::getInstance();
                $customerSession = $objectManagerlogin->get('Magento\Customer\Model\Session');
            ?>
        <?php 
            if($customerSession->isLoggedIn()) {
            $customerSession = $objectManagerlogin->get('Magento\Customer\Model\Session');
        ?>
           <h2 class="name"><?php echo __('Hala'); echo ' '.$customerSession->getCustomer()->getFirstname(); ?>!</h2>
           <p class="email"><?php echo $customerSession->getCustomer()->getEmail(); ?></p>
        <?php
        }else{
            ?>
            <div class="hi-text">
                <h2><?php echo __('Hi, We Are Dreamarkets'); ?></h2>
            </div>
            <?php
        }    
        ?>
    </div>
    <ul class="mobile-aloteam">
        <li class="home"><a href="<?php echo $block->getUrl(''); ?>"><?php echo __('Home') ?></a></li>

        <?php
                $objectManagerlogin = \Magento\Framework\App\ObjectManager::getInstance();
                $customerSession = $objectManagerlogin->get('Magento\Customer\Model\Session');
            ?>
        <?php if($customerSession->isLoggedIn()) { ?>
        <li class="account">
            <div class="settting-switcher">
                <div class="dropdown-toggle toggle-tab">
                    <button aria-label="Back To Main Menu" class="returnCta"><i
                            class="icon icon-angle-left "></i><?php echo __('Back To Main Menu') ?></button>
                    <div class="text-setting account"><a href="#"><?php echo __('Account') ?></a></div>
                </div>
                <div class="dropdown-switcher toggle-content">
                    <div class="top-links-alo">
                        <div class="header-top-link">
                            <ul class="my-account-links">
                                <li class="order"><a
                                        href="<?php echo $block->getUrl('sales/order/history'); ?>"><?php echo __('Orders') ?></a>
                                </li>
                                <li class="order"><a
                                        href="<?php echo $block->getUrl('customer/address'); ?>"><?php echo __('Addresses') ?></a>
                                </li>
                                <li class="order"><a
                                        href="<?php echo $block->getUrl('vault/cards/listaction'); ?>"><?php echo __('Payment') ?></a>
                                </li>
                                <li class="order"><a href="#"><?php echo __('Dream Credits') ?></a></li>
                                <li class="order"><a
                                        href="<?php echo $block->getUrl('csmessaging/customer/ainbox'); ?>"><?php echo __('Inbox') ?></a>
                                </li>
                                <li class="order"><a
                                        href="<?php echo $block->getUrl('customer/account'); ?>"><?php echo __('Profile') ?></a>
                                </li>
                            </ul>
                            <a
                                href="<?php echo $block->getUrl('customer/account/logout'); ?>"><?php echo __('LOGOUT') ?></a>
                        </div>
                    </div>
                </div>
            </div>

        </li>
        <li class="wishlist"><a href="<?php echo $this->getUrl('wishlist') ?>"><?php echo __('Wishlist') ?></a></li>
        <?php }else { ?>
        <li class="sign-in"><a
                href="<?php echo $block->getUrl('customer/account/login'); ?>"><?php echo __('Sign In') ?></a></li>
        <li class="sign-out"><a
                href="<?php echo $block->getUrl('customer/account/create'); ?>"><?php echo __('Sign Up') ?></a></li>
        <?php
                }
                ?>


        <li class="cart"><a href="<?php echo $block->getUrl('checkout/cart'); ?>"><?php echo __('Cart'); ?></a></li>
    </ul>
    <?php $layout = $block->getLayout(); ?>
    <div class="section-items <?= /* @escapeNotVerified */ $groupCss ?>-items"
        data-mage-init='<?= /* @escapeNotVerified */ $groupBehavior ?>'>
        <?php foreach ($detailedInfoGroup as $name):?>
        <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html) && ($block->getUseForce() != true)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
        <div class="section-item-title <?= /* @escapeNotVerified */ $groupCss ?>-item-title" data-role="collapsible">
            <a class="<?= /* @escapeNotVerified */ $groupCss ?>-item-switch" data-toggle="switch"
                href="#<?= /* @escapeNotVerified */ $alias ?>"><?= /* @escapeNotVerified */ $label ?></a>
        </div>
        <div class="section-item-content <?= /* @escapeNotVerified */ $groupCss ?>-item-content"
            id="<?= /* @escapeNotVerified */ $alias ?>" data-role="content">
            <?= /* @escapeNotVerified */ $html ?></div>
        <?php endforeach;?>
    </div>
    <ul class="mobile-bottom-cuong">
        <li class="sell"><a href="/csmarketplace/vendor/index/"><?php echo __('Sell'); ?></a></li>
        <li class='mobile-bottom'>
            <ul>
                <li class="help"><a href="#"><?php echo __('Help'); ?></a></li>
                <li class="contact-us"><a href="#"><?php echo __('Contact Us'); ?></a></li>
            </ul>

        </li>
    </ul> 
</div>
<script>
require(["jquery"], function($){
	$(document).ready(function() {
	    $('.close_mobile').click(function(){
            if($('html').hasClass('nav-open')){
                $('html').removeClass('nav-before-open');
                $('html').removeClass('nav-open');
            }
        })
	});
});
</script>
<?php endif; ?>