<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMessaging
 * @author      CedCommerce Core Team <connect@cedcommerce.com >
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
?>
<div class="page-main-actions">
    <div class="page-actions">
        <div class="page-actions-inner">
            <div class="page-actions-buttons">
                <button id="add" title="<?php echo __('Compose');?>" type="button" class="action- scalable primary"
                        onclick="location.href='<?php echo $this->getUrl('customer/index/index');?>'">
                    <span><?php echo __('Compose');?></span>
                </button>
            </div>
        </div>
    </div>
</div>
<?php echo $block->getChildHtml('grid') ?>

